name: Build docker image and run tests

on: [push, pull_request]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Cleanup untagged images older than 1 week
        uses: snok/container-retention-policy@v2
        with:
          image-names: Amelie-GDPR-document
          cut-off: 1 week ago UTC
          account-type: org
          org-name: Inter-Actief
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token
          untagged-only: true

      - name: Cleanup tagged images (except main) older than 1 month
        uses: snok/container-retention-policy@v2
        with:
          image-names: Amelie-GDPR-document
          cut-off: 1 month ago UTC
          account-type: org
          org-name: Inter-Actief
          token: ${{ secrets.GITHUB_TOKEN }}
          token-type: github-token
          skip-tags: main

